all: ./neurolife/*.cpp
	g++ -std=c++14 -DLINUX ./neurolife/*.cpp -o ./bin/ubuntu/nlife
d:	./neurolife/*.cpp
	g++ -g -std=c++14 -DLINUX ./neurolife/*.cpp -o ./bin/ubuntu/nlifed
c: 
	rm -rf /bin/ubuntu/nlife